name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: | 
        make
        ls -l
    - name: Create Release
      # You may pin to the exact commit or the version.
      # uses: ncipollo/release-action@7c5046364401a3e122086927d07617a3d756b658
      uses: ncipollo/release-action@v1.8.4
      with:
        artifacts: measure-pipebuf, pipebuf-constants
        token: ${{ github.token }}
        tag:  v1.0
